modLoader = "javafml"
loaderVersion = "[${fml_version},)"
issueTrackerURL = "https://github.com/YukkuriC/BotaniaOverpowered/issues"
license = "MIT"

[[mods]]
modId = "botania_overpowered"
version = "${version}"
displayName = "BotaniaOverpowered"
authors = "YukkuriC"
description = '''
An addon of Botania about some enhancements / un-nerfs which are kind of overpowered.
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/hpVTpNjB/forge_updates.json"
displayURL = "https://modrinth.com/mod/botaniaoverpowered"

[[dependencies.botania_overpowered]]
modId = "forge"
mandatory = true
versionRange = "[${fml_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botania_overpowered]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botania_overpowered]]
modId = "botania"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

